version: '3.8'
services:
  stats-server:
    build: stats/stats-server/
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  main-service:
    build: main-service/
    container_name: main_service
    ports:
        - "8080:8080"
    depends_on:
        - main-db
    environment:
        ##- SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/postgres
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - STATS-SERVER.URL=http://stats-server:9090
  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres