version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats_server_image1
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  main-service:
    build: main-service
    image: main_service_image
    container_name: main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
        - SHAREIT_SERVER_URL=http://server:8080

