version: '3.8'
services:
  stats-server:
    build: stats/stats-server/
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  main-service:
    build: main-service
    image: main-service
    container_name: main_service
    ports:
      - "8080:8080"
    depends_on:
        - ewm-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/postgres
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=user
        - STATS-SERVER.URL=http://stats-server:9090

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres