--DROP TABLE HITS CASCADE;

CREATE TABLE IF NOT EXISTS HITS(
hit_id INTEGER generated by default as identity primary key,
app varchar(100) not null,
uri varchar(100) not null,
ip varchar(100) not null,
times timestamp WITHOUT TIME ZONE
);